### ISSUE TITLE
Alias method fail 

### ISSUE THREAD

**Issue by bubodlack** [segersniels/supdock#6]
```bash
~ % docker run -v index-data:/volume -v /tmp:/backup --rm loomchild/volume-backup backup solr-volume
2.2.6
~ % docker run -v 
2.2.6
~ % supdock -v
2.2.6
```

:(

**Comment by segersniels** [comment]
@bubodlack That doesn't seem right indeed! Version `2.2.7` is live and should fix the issue. Can you update and confirm this fixes your issue?

**Comment by bubodlack** [comment]
I've tried last version and the bug is gone 

thanks
